// Notas do apresentador por slide. Índices [n] referem-se ao dump de
// dist/projeto-pcc.docx via `python tools/docx_prose.py dump`. Preservar.

export const NOTES: string[] = [
  `<b>Capa.</b> Título, autor e orientadora [4][5][12]. Projeto de pesquisa da disciplina de Metodologia Científica, curso de Sistemas para Internet, IFMT Campus Octayde Jorge da Silva [11].`,
  `<b>Justificativa [26].</b> "No FrontierHarness (Runta, 2026), doze configurações de nove harnesses sobre o mesmo modelo ficam entre 50,0% e 66,7% de aprovação, e o custo por tarefa concluída vai de US$ 1,05 a US$ 18,34, uma razão de 17,5x calculada pelo autor." Também [52]: Codex 66,7% a US$ 3,47; Claude Code 63,3% a US$ 18,34 (5,3x, cálculo do autor). Os demais valores das barras (Pi, oh-my-pi, DSH Creator, Exo, OpenCode) vêm da página wiki/sources/frontierharness-runta-2026.md, mesmo post; 30 tarefas e 1 tentativa por célula também vêm dessa página. Quem paga é o desenvolvedor e a empresa [27].`,
  `<b>Referencial [49][50].</b> Ning et al. (2026, §2): um harness "converte um modelo de linguagem sem estado em um agente funcional ao ancorar suas saídas em execução externa, estado persistente e realimentação verificável". Wang et al. (2026): monta os prompts, gerencia o estado, invoca as ferramentas e coordena o laço. Lin et al. (2026, §1): prompt de sistema, ferramentas (sistema de arquivos e shell), middleware de contexto, execução e recuperação; "conjunto de componentes externos ao modelo e editáveis". [51]: é esse conjunto, e só ele, que varia entre os braços. O proxy externo é o instrumento do projeto [63], fora do harness.`,
  `<b>Justificativa [27], tema [29], problema [31], objetivo geral [33].</b> [27]: "Quem paga essa conta é o desenvolvedor, na assinatura pessoal, e a empresa que adota a ferramenta em escala; conhecer o harness virou parte do ofício. As comparações publicadas contrastam ferramentas de equipes diferentes e não dizem qual decisão de projeto pesa." Ler o problema na íntegra: "Para o desenvolvedor ou a empresa que já escolheu o modelo, quanto do custo por tarefa concluída e da taxa de sucesso do agente de codificação é determinado pelo harness adotado? E quais decisões de projeto do harness respondem por essa diferença, de modo que seja possível agir sobre elas?"`,
  `<b>Objetivos específicos [35]–[41].</b> 1 instrumento externo idêntico para todos; 2 suíte com objetivos numerados, crédito parcial e oráculo independente dos testes do agente; 3 harness mínimo ReAct como controle; 4 mesma suíte, mesmo modelo, repetição e dispersão; 5 segundo modelo, ordenação mantida ou invertida; 6 divergência custo relatado vs medido; 7 publicar runner, dados e scripts a custo zero.`,
  `<b>Hipóteses [45][46].</b> H1 refutada se os intervalos de Succ/Mtok dos braços se sobrepuserem ao longo de toda a suíte. H2 refutada se pi e oh-my-pi não diferirem em Succ/Mtok, "mesmo que a Camada 1 confirme que o fork envia uma carga maior por requisição" — desfecho possível e reportável, pois o oh-my-pi pode compensar em menos passos. Dados do gráfico: layer1/data/first_request.csv e step_growth.csv (pi 5.676 bytes / 1.228 tokens; oh-my-pi 64.945 bytes / 16.714 tokens; 4 vs 11 esquemas; razão 11,4x em bytes). Ponto externo: FrontierHarness, Pi 60,0%/US$ 2,43 vs oh-my-pi 56,7%/US$ 4,75 (wiki/entities/oh-my-pi.md).`,
  `<b>Referencial [49]–[55].</b> Yang 2024: interface modelo-ambiente como objeto de projeto. Lin 2026 Tabela 1: 47,2% OpenCode a 71,9% Codex, GPT-5.4, Terminal-Bench 2, 89 tarefas, 24,7 pp (cálculo do autor). Zhang 2026: Binding Constraint Thesis, com modelos de fronteira comparáveis a parcela do harness é frequentemente comparável ou maior. Alier Forment 2026: sem MCP 5,0x a 28x mais barato. HarnessRank: ordena por aprovação, custo ao lado. Databricks apud Earendil: >2x em alguns casos. Ning 2026 §5.2.1/§5.2.7: lacuna de atribuição, pede métricas por componente. Lee 2026 Tabela 7: 76,4% vs 74,7% (TerminalBench-2, 89 tarefas, Claude Opus 4.6). Kapoor 2024/2025: custo ignorado, comparações entre harnesses raras; Anthropic melhor com BrowserUse, OpenAI com SeeAct. Runta 2026: cache 25,0% ponderado vs 67,8% na célula mediana do Claude Code.`,
  `<b>Classificação [43][57] e declaração de IA [58].</b> [57]: "Quanto à natureza, esta é uma pesquisa aplicada [...]. Quanto à abordagem, combina o quantitativo e o qualitativo. [...] Quanto aos objetivos, é exploratória, porque a comparação com linhagem de harness fixa não tem precedente publicado. Quanto aos procedimentos, é experimental, com variável independente manipulada (o harness), variáveis controladas (modelo, tarefa e limites) e um grupo de controle. Quanto ao método, é dedutivo" (Gil, 2022; Prodanov; Freitas, 2013). [58]: LLM Wiki no repositório (YuukiFST, 2026); Portaria CNPq 2.664/2026 pede declaração com ferramenta e finalidade (Brasil, 2026); ferramenta Claude Code, finalidade síntese e conferência de fontes; o autor responde pelo texto final.`,
  `<b>Método [59][63][64].</b> Camada 1: forma da requisição contra endpoint simulado que não encaminha nada ao modelo; determinística, sem cota. Camada 2: desfecho contra o modelo real, estocástica, consome cota. "Mais bytes por requisição não significam, por si, resultado pior." Proxy reverso força o relatório de uso, conta tokens sobre os bytes transmitidos com um único tokenizador; o gateway injeta conteúdo, deslocamento aditivo por requisição que não se cancela em razão [63]. Limite único: relógio de parede 3x a mediana do harness zero; sem teto de passos [64].`,
  `<b>Braços [60], suíte [61], limite [64], células [65], classes [67].</b> [64]: "Um único limite será imposto, idêntico para todos os braços. É um relógio de parede, cujo valor será três vezes a mediana que o harness zero gastar nas tarefas-piloto. O número de passos não será limitado, porque um teto de passos é ele próprio uma decisão de projeto de harness." Parâmetros de amostragem registrados, não normalizados (Miller, 2024). Harness zero: laço observar/agir, 3 ferramentas (ler, escrever, executar), sem planejamento, compactação, retry ou chamada auxiliar, < 400 linhas com portão de CI. Adaptadores pi e oh-my-pi escritos no projeto (o executor Pier não os traz). Suíte: 8 tarefas Python do DeepSWE congeladas; DeepSWE tem 113 tarefas, 91 repositórios, 668 linhas em média vs 32,8 no SWE-bench (~20x, cálculo do autor). Crédito parcial é adaptação (DeepSWE grada binário, §8). Cada célula (braço, tarefa, nível) n ≥ 3 após descartes; dois níveis de modelo gratuitos no mesmo gateway [62]. Classes de execução [67]: falhada = resultado com escore zero; descartada = medição inconfiável.`,
  `<b>Métrica e estatística [55][66].</b> Succ/Mtok de Lin et al. (2026): sucessos por milhão de tokens. Wilcoxon dos postos sinalizados, bilateral, α = 0,05, sobre o Succ/Mtok por tarefa; não paramétrico porque 8 pares não sustentam suposição distribucional; pareado porque a dificuldade da tarefa é o maior fator de perturbação (Miller, 2024). MDE ≈ 0,81σ com n = 3 e 8 tarefas. Predições pré-registradas por nível. O painel é simulação: dificuldades das 8 tarefas são multiplicadores fixos ilustrativos; valor crítico de W para n = 8, bilateral, α = 0,05 é 3.`,
  `<b>Limitações [69].</b> Quatro declaradas: efeito específico do modelo (pode inverter; objetivo 5); modelos pequenos em aberto (único viável treinado dentro de um braço); valores absolutos não comparáveis ao placar do DeepSWE (linhas de base com harness de ferramenta única; dólares externos vêm de outros modelos e níveis pagos); custo em dinheiro como contrafactual rotulado. Variância como principal ameaça [65]. O gráfico de barras do slide é ilustrativo (forma de uma inversão), sem dados do experimento; a evidência real de inversão é Kapoor et al. (2025) [55].`,
  `<b>Orçamento [71]–[83]:</b> inferência R$ 0,00 (nível gratuito do gateway), executor e benchmark R$ 0,00 (Pier e DeepSWE, Apache-2.0), máquinas R$ 0,00 (estação NixOS e estação Windows, já disponíveis). Cota gratuita é o limite vinculante; lotes ao longo de dias. <b>Cronograma [85]–[152]:</b> set–out leitura e definição do tema; out–nov instrumento e harness zero; escrita da introdução em nov [114], referencial em nov, material e método nov–dez; matriz dez–jan; análise, referências e revisão final em jan.`,
  `<b>Referências [155]–[180].</b> Lista completa com 25 entradas no projeto. Preprints marcados. Aqui só as citadas nos slides: sem as três normas ABNT, IFMT (2022), Earendil, HarnessRank e Opencode, citadas só no texto do projeto.`,
  `<b>Fecho.</b> Retomar o problema [31] e o produto [57]: um critério de escolha que um desenvolvedor ou uma empresa poderá aplicar. Repositório YuukiFST/harness-bench [179].`,
];
